// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/trigger/v1/trigger.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request must contain param
type OnTriggerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Param string `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
}

func (x *OnTriggerRequest) Reset() {
	*x = OnTriggerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_trigger_v1_trigger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTriggerRequest) ProtoMessage() {}

func (x *OnTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_trigger_v1_trigger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTriggerRequest.ProtoReflect.Descriptor instead.
func (*OnTriggerRequest) Descriptor() ([]byte, []int) {
	return file_api_trigger_v1_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *OnTriggerRequest) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

// Response contains automated test assertion
type OnTriggerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OnTriggerReply) Reset() {
	*x = OnTriggerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_trigger_v1_trigger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnTriggerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnTriggerReply) ProtoMessage() {}

func (x *OnTriggerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_trigger_v1_trigger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnTriggerReply.ProtoReflect.Descriptor instead.
func (*OnTriggerReply) Descriptor() ([]byte, []int) {
	return file_api_trigger_v1_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *OnTriggerReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_trigger_v1_trigger_proto protoreflect.FileDescriptor

var file_api_trigger_v1_trigger_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x70, 0x69, 0x2e, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x10,
	0x4f, 0x6e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x2a, 0x0a, 0x0e, 0x4f, 0x6e, 0x54, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x32, 0x74, 0x0a, 0x07, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x69, 0x0a,
	0x09, 0x4f, 0x6e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e,
	0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x6f, 0x6e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
	0x2f, 0x7b, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x7d, 0x42, 0x32, 0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2e,
	0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1e, 0x48, 0x6f,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x46, 0x6f, 0x75, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_trigger_v1_trigger_proto_rawDescOnce sync.Once
	file_api_trigger_v1_trigger_proto_rawDescData = file_api_trigger_v1_trigger_proto_rawDesc
)

func file_api_trigger_v1_trigger_proto_rawDescGZIP() []byte {
	file_api_trigger_v1_trigger_proto_rawDescOnce.Do(func() {
		file_api_trigger_v1_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_trigger_v1_trigger_proto_rawDescData)
	})
	return file_api_trigger_v1_trigger_proto_rawDescData
}

var file_api_trigger_v1_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_trigger_v1_trigger_proto_goTypes = []interface{}{
	(*OnTriggerRequest)(nil), // 0: api.trigger.v1.OnTriggerRequest
	(*OnTriggerReply)(nil),   // 1: api.trigger.v1.OnTriggerReply
}
var file_api_trigger_v1_trigger_proto_depIdxs = []int32{
	0, // 0: api.trigger.v1.Trigger.OnTrigger:input_type -> api.trigger.v1.OnTriggerRequest
	1, // 1: api.trigger.v1.Trigger.OnTrigger:output_type -> api.trigger.v1.OnTriggerReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_trigger_v1_trigger_proto_init() }
func file_api_trigger_v1_trigger_proto_init() {
	if File_api_trigger_v1_trigger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_trigger_v1_trigger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTriggerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_trigger_v1_trigger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnTriggerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_trigger_v1_trigger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_trigger_v1_trigger_proto_goTypes,
		DependencyIndexes: file_api_trigger_v1_trigger_proto_depIdxs,
		MessageInfos:      file_api_trigger_v1_trigger_proto_msgTypes,
	}.Build()
	File_api_trigger_v1_trigger_proto = out.File
	file_api_trigger_v1_trigger_proto_rawDesc = nil
	file_api_trigger_v1_trigger_proto_goTypes = nil
	file_api_trigger_v1_trigger_proto_depIdxs = nil
}
