// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.0

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type TriggerHTTPServer interface {
	OnTrigger(context.Context, *OnTriggerRequest) (*OnTriggerReply, error)
}

func RegisterTriggerHTTPServer(s *http.Server, srv TriggerHTTPServer) {
	r := s.Route("/")
	r.GET("/onTrigger/{param}", _Trigger_OnTrigger0_HTTP_Handler(srv))
}

func _Trigger_OnTrigger0_HTTP_Handler(srv TriggerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OnTriggerRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.trigger.v1.Trigger/OnTrigger")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OnTrigger(ctx, req.(*OnTriggerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OnTriggerReply)
		return ctx.Result(200, reply)
	}
}

type TriggerHTTPClient interface {
	OnTrigger(ctx context.Context, req *OnTriggerRequest, opts ...http.CallOption) (rsp *OnTriggerReply, err error)
}

type TriggerHTTPClientImpl struct {
	cc *http.Client
}

func NewTriggerHTTPClient(client *http.Client) TriggerHTTPClient {
	return &TriggerHTTPClientImpl{client}
}

func (c *TriggerHTTPClientImpl) OnTrigger(ctx context.Context, in *OnTriggerRequest, opts ...http.CallOption) (*OnTriggerReply, error) {
	var out OnTriggerReply
	pattern := "/onTrigger/{param}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.trigger.v1.Trigger/OnTrigger"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
