// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TriggerClient is the client API for Trigger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TriggerClient interface {
	// http api trigger automated test
	OnTrigger(ctx context.Context, in *OnTriggerRequest, opts ...grpc.CallOption) (*OnTriggerReply, error)
}

type triggerClient struct {
	cc grpc.ClientConnInterface
}

func NewTriggerClient(cc grpc.ClientConnInterface) TriggerClient {
	return &triggerClient{cc}
}

func (c *triggerClient) OnTrigger(ctx context.Context, in *OnTriggerRequest, opts ...grpc.CallOption) (*OnTriggerReply, error) {
	out := new(OnTriggerReply)
	err := c.cc.Invoke(ctx, "/api.trigger.v1.Trigger/OnTrigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TriggerServer is the server API for Trigger service.
// All implementations must embed UnimplementedTriggerServer
// for forward compatibility
type TriggerServer interface {
	// http api trigger automated test
	OnTrigger(context.Context, *OnTriggerRequest) (*OnTriggerReply, error)
	mustEmbedUnimplementedTriggerServer()
}

// UnimplementedTriggerServer must be embedded to have forward compatible implementations.
type UnimplementedTriggerServer struct {
}

func (UnimplementedTriggerServer) OnTrigger(context.Context, *OnTriggerRequest) (*OnTriggerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnTrigger not implemented")
}
func (UnimplementedTriggerServer) mustEmbedUnimplementedTriggerServer() {}

// UnsafeTriggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TriggerServer will
// result in compilation errors.
type UnsafeTriggerServer interface {
	mustEmbedUnimplementedTriggerServer()
}

func RegisterTriggerServer(s grpc.ServiceRegistrar, srv TriggerServer) {
	s.RegisterService(&Trigger_ServiceDesc, srv)
}

func _Trigger_OnTrigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnTriggerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TriggerServer).OnTrigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.trigger.v1.Trigger/OnTrigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TriggerServer).OnTrigger(ctx, req.(*OnTriggerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Trigger_ServiceDesc is the grpc.ServiceDesc for Trigger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trigger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.trigger.v1.Trigger",
	HandlerType: (*TriggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnTrigger",
			Handler:    _Trigger_OnTrigger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/trigger/v1/trigger.proto",
}
